### ISSUE TITLE
Personal resource display broken with tidy 6.20.1

### ISSUE THREAD

**Issue by xxroots** [ImogenBits/tidyplates#23]
Hi, i think we had this issue before, latest tidy plates file breaking the personal resource display bars and buffs. Rolled back to previous tidyplates version and its ok again. thanks.

**Comment by ImogenBits** [comment]
Can you please describe the issue in more detail? It seems to be working fine for me and I need to be able to recreate it to fix it.

**Comment by ImogenBits** [comment]
Nevermind, figured out the problem and fixed it. New realease with the fix is uploading at the moment.

**Comment by xxroots** [comment]
Problem persist with latest release.

**Comment by ImogenBits** [comment]
Are you on version 6.20.2? Can you please describe the steps you take to reproduce this bug? In every situation I try this out it works fine for me.

**Comment by xxroots** [comment]
![WoWScrnShot_112620_113552](https://user-images.githubusercontent.com/73133664/100375966-ab689300-2fdc-11eb-9b8c-22caa9b55a5a.jpg)

This is the personal resource display option in the blizzard interface.

![WoWScrnShot_112620_113529](https://user-images.githubusercontent.com/73133664/100375994-bd4a3600-2fdc-11eb-87bd-87f48f982b1b.jpg)

This is how it should look under my toon.

![WoWScrnShot_112620_114155](https://user-images.githubusercontent.com/73133664/100376037-cdfaac00-2fdc-11eb-951c-6ff480f5aeca.jpg)

And this is how it looks with the latest 2 tidy plates updates, like i said, reverting to 6.20.0 fix the problem.

Hope this helps, thanks in advance.

**Comment by ImogenBits** [comment]
Are you doing anything specific to make this happen? seems to be working fine in the second, but not the third screenshot. The more detail you give me what you do to make this happen the faster I can figure out what is causing it.

**Comment by xxroots** [comment]
Just going into combat, those bars trigger in combat only. Not even using any special move, just normal attacks. 
The third screenie is the one with the latest tidy plates updates and i think the one causing the problem. Im gonna disable all of my addons but tidy plates and be back at you with the results.

**Comment by xxroots** [comment]
![WoWScrnShot_112620_125627](https://user-images.githubusercontent.com/73133664/100381640-6433cf80-2fe7-11eb-81b1-8542edbde5f6.jpg)

Ok no addons, only Tidy plates up and the blizzard personal resource bars still broken(only showing energy, mana or rage). Hope this helps.

**Comment by Naturage** [comment]
Just wanted to confirm this issue exists. My version is 6.20.2, and I've tested on various specs - druid in all shapes and DK. Tested addons by disabling everything except Tidyplates and by trying alternate themes (persists with all base 4).

On one occasion the health bar appeared when I entered combat and persisted until next occasion I reloaded (think it was swapping instances). I was unable to reproduce this, so I'd write it off.

**Comment by Anzaru** [comment]
I am also having this problem, would also like to add that the problem is fixed when rolling back to version 6.20.0. The two versions after that have the issue.

**Comment by daggin** [comment]
![wtf](https://user-images.githubusercontent.com/75466030/101124879-bd35d180-35ac-11eb-83cb-df271398fdbf.PNG)

Rogue is also having this problem. It is also forcing my default, in-game resource ABOVE the tidyplates enemy health bar. where I can't see it, I need it for anima charges, as tidyplates still doesn't support anima charges for Kyrian Rogue.

**Comment by grimwall** [comment]
Just to chime in that this issue persists (DH), but hard to reproduce. The issue crops up randomly. Are there logs we can check for add on exceptions? That might help with the issue...

**Comment by nakinacho** [comment]
I think it's wow client bug, not the tidy plates, because i faced this problem before installing addon

**Comment by MrMontte** [comment]
The bug has popped back up for me recently. It'll do it at random times, so I don't know what the cause is, just that it's from tidyplates.

**Comment by MrMontte** [comment]
So is this going to get addressed at all? I like using tidy plates, but this is getting really annoying.

**Comment by ImogenBits** [comment]
I'm currently unable to reproduce this bug. If you want to get it fixed, please submit more detailed reports of what exactly you do to have this happen, your settings (both TidyPlates settings and CVars, can upload the files somewhere), your classes/specs, how often this happens, etc.

**Comment by wickermoon** [comment]
I have the same issue. I log into the game, select one of the training dummies and it only shows the resource bar. A "quickfix" is to go into the interface menu, while the PRD is showing, and turn the Personal Resource Display off and back on again. But that is too frequently necessary to be a sensible fix.

I was wondering, why Tidy Plates wouldn't alter the PRD anyway? There are a lot of Nameplates-mods that do that (KuiNameplates, for example) and I would love for Tidy Plates to do that as well, maybe even showing health and resource texts on the PRD, as well.

In order to more easily reproduce, I changed the display setting for the PRD to show when I have a target selected, maybe that'll help with reproduction. Also, I'm playing DH, but I had the same problem on my DK.

**Comment by ImogenBits** [comment]
yeah, not theming the personal resource display is not my decision and I'm not entirely sure why it was done. But doing that would involve some work since you'd want it to show more than just a regular nameplate (I think, I don't actually use it myself). If you have any suggestions on what you'd want it to look like, you can leave them in this issue #7.

**Comment by TranquilHermit** [comment]
Just adding to this - I am still having this issue as well.  When going back to 6.20.0  the issue goes away.

Also it occurs with no other addons installed.
