### ISSUE TITLE
Normal Nameplate Randomly Appears

### ISSUE THREAD

**Issue by GriimZz** [ImogenBits/tidyplates#25]
For some reason the normal wow nameplates randomly pops up under my tidyplates nameplate in PvP , and im yet to know why , i just came back for shadowlands and this issue has been happening since the last time i played , is there a known way to fix this bug ? Maybe go back to an older version ?
![tidyplate](https://user-images.githubusercontent.com/75138306/100475527-3fb91f80-30db-11eb-8b5a-1dc5dc18a8c4.png)

**Comment by ImogenBits** [comment]
This is very similar to a bug I've already fixed so I think I'll be able to fix this fairly quickly too. Don't think any old version would work though.

**Comment by GriimZz** [comment]
Alright thank you very much , hope its fixed soon!

**Comment by GriimZz** [comment]
@ImogenBits Have been updating the addon every time its possible and the issue is still not fixed , do you have an eta on the fix ?

**Comment by luringen** [comment]
Same issue for me as for now, when monk use Storm, Earth, and Fire it seems to make 2 hp bars, one tidy plate and one standard hp bar

**Comment by ImogenBits** [comment]
I'm not able to reproduce the issue unfortunately. If you can give me any more detail like [this wiki page explains](https://github.com/ImogenBits/tidyplates/wiki/Bug-Reports) I'll look into it.
Closing this for now, if it's still an issue I will reopen it.

**Comment by luringen** [comment]
> I'm not able to reproduce the issue unfortunately. If you can give me any more detail like [this wiki page explains](https://github.com/ImogenBits/tidyplates/wiki/Bug-Reports) I'll look into it.
> Closing this for now, if it's still an issue I will reopen it.

It happens only with Shaman/Monk, in arenas mostly, when they pop pets. like earth wind fire, and earth elemental. 
![WoWScrnShot_030121_142709](https://user-images.githubusercontent.com/7968409/109503666-d4e10100-7a9a-11eb-95fd-cf8e9ae32c08.jpg)
