### ISSUE TITLE
Debuffs with infinite duration behave erratically

### ISSUE THREAD

**Issue by Rhykes** [ImogenBits/tidyplates#60]
Debuffs that have an unlimited duration can sometimes behave very strangely on TidyPlates, showing a phantom timer when there isn't any or disappearing entirely for a few moments after it "expires" before reappearing. 

For targets that live a while, debuffs that initially behave correctly might suddenly switch to this bugged state before eventually correcting itself after it "expires" and reappears.

I have not been able to identify what exactly causes this as sometimes it functions perfectly fine, but it's common enough as an affliction warlock with Absolute Corruption talented that it is pretty easy to reproduce numerous times over the course of normal play. Since this bug is pretty old and I've mostly come to expect it and tune it out, I can't say with 100% certainty if this applies to ALL debuffs with infinite duration or just Absolute Corruption, but I am *pretty* confident this can occur on all of them.

Seed of Corruption detonating seems to apply a bugged corruption on the primary target fairly consistently, but this is definitely not the specific trigger as it can happen without ever pressing it.

If I find out anything more I'll let you know, hopefully this is enough. Thank you for maintaining this addon!

![tidyplatesdebuffbug](https://user-images.githubusercontent.com/18037793/129286894-2f0888e4-14fc-4ec1-8b01-322d204b7b83.png)

**Comment by ImogenBits** [comment]
should be fixed with this update, though I'm not super confident. If the issue (or a similar one) persists please comment here again :)

**Comment by Rhykes** [comment]
Hey, sorry it took so long to get back to you. Unfortunately with version 6.20.10, this issue is not fixed. As before, sometimes they work correctly, but other times it thinks it has a duration and will behave strangely until the fake duration finishes and it resets itself.
